### ISSUE TITLE
Uniqueness of DHistogramAction_AnalyzeCutActions

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_root_analysis#134]
Trying to see the output of DHistogramAction_AnalyzeCutActions for measured and kinfit data has exposed some issue.
  The following code either produces only one histogram directory in the outfile or it can produce 2 directories with vastly different statistics.                    

	dAnalyzeCutActions = new DHistogramAction_AnalyzeCutActions( dAnalysisActions, dComboWrapper, false, 0, MyOmega, 1000, 0.0, 4.0, "CutActionEffect" );
	dAnalyzeCutActions = new DHistogramAction_AnalyzeCutActions( dAnalysisActions, dComboWrapper, true,  0, MyOmega, 1000, 0.0, 4.0, "CutActionEffect_kinfit" );

**Comment by aaust** [comment]
You are allocating 2 different memory blocks to the same pointer dAnalyzeCutActions.
You could try to make 2 completely separate AnalyzeCutActions with different names, that are both initialized, reset and performed. No guarantee if that will work though.

**Comment by markdalton** [comment]
I will try that and report back.

**Comment by aaust** [comment]
@markdalton Is this still an issue?

**Comment by markdalton** [comment]
No, you solved my issue.  Thanks.
I didn't try 2 separate AnalyzeCutActions.
