### ISSUE TITLE
tree_to_amptools current segfaults on Thrown_Tree

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_root_analysis#151]
Between version_4.36.0 and version_4.38.0 tree_to_amptools stopped being able to handle the Thrown_Tree and now immediately segfaults on files that used to work fine.

**Comment by aaust** [comment]
Can you please provide an example for the Thrown_Tree file?

**Comment by markdalton** [comment]
The following is a command that I believe worked last year, but I could be mistaken.

tree_to_amptools /work/halld/home/dalton/datafiles/gluex/physics/omega/MonteCarlo/thrown/SDME_pi0pippim__B4__2018-08_pol.root Thrown_Tree 14 7 8 9

I have verified that the behavior changes between version_4.36.0 and version_4.38.0.

version_4.38.0: there is a segfault and stack trace and no output file is produced.

version_4.36.0: there is an error invalid pointer and stack trace and an output file is produced.

Smaller file for testing:
tree_to_amptools $DATAFILESOMEGA/MonteCarlo/SDME_omega_3pi_201808_thrown/tree_RF/tree_pi0pippim__B4_gen_amp_051768.root Thrown_Tree 14 7 8 9

**Comment by aaust** [comment]
Reading the generated info from the Thrown_Tree requires the '-gen' flag now. This works for me:

` tree_to_amptools /work/halld/home/dalton/datafiles/gluex/physics/omega/MonteCarlo/thrown/SDME_pi0pippim__B4__2018-08_pol.root Thrown_Tree -gen 14 7 8 9`

I agree that this could have been better documented.

**Comment by aaust** [comment]
Correction: the '-gen' flag restores the error you see in 4.36.0. There is still a problem with the decaying pi0.

**Comment by aaust** [comment]
There are rare cases (<1%) where the number of thrown particles in your input tree is actually 7 and not 6:
` Thrown_Tree->Draw("NumThrown")`

These are events, where the thrown pi0 decays into e+e-gamma in geant. I assume, we want to suppress other decays from the thrown sample, don't we?

**Comment by markdalton** [comment]
I spoke to Alex and the problem here is that in events were pi0 decays into e+e-gamma they final state particles end up in the tree in an order which means that tree_to_amptools cannot transparently deal with them the same way as for pi0 -> gg.  This explains why the program crashes on exit, but also means that the crash cannot be ignored.

**Comment by aaust** [comment]
In this branch, all events that have a different topology than the very first event are skipped:
https://github.com/JeffersonLab/gluex_root_analysis/tree/tree_to_amptools_dalitz

It fixes the crash on exit for this issue. Supplying the full decay tree on the command line is a larger project.

**Comment by aaust** [comment]
#152 fixed this issue
