### ISSUE TITLE
Failure analyzing thrown MC trees

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/gluex_root_analysis#170]
The latest PR #169 causes a crash when analyzing thrown MC trees. To avoid the crash, one has to set the flag `dSkipNoTriggerEvents = false;` in the Init() function of the DSelector.

We could add this to the example code generated by MakeDSelector, but everybody would have to modify their existing DSelectors. In search for more elegant solution.

**Comment by denehoffman** [comment]
Would it make sense to add a conditional into the `DSelector::Init` function like `if (dTreeInterface->Get_Branch("NumCombos") == NULL) dSkipNoTriggerEvents = false;`? That way DSelectors that inherit will set it automatically, and if someone wants to opt out for some reason, they can just add it to their own code after it calls the superclass Init.

**Comment by aaust** [comment]
@sdobbs chose a more elegant route
