### ISSUE TITLE
double free or corruption error when creating flat trees with DSelectors

### ISSUE THREAD

**Issue by dancbart** [JeffersonLab/gluex_root_analysis#173]
When unboxing a DSelector to produce flat trees I receive this error:
'double free or corruption'

Changes made the new, unchanged, DSelector created from 2018-08 version 23 root file:
Remove entry for 'dOutputFilename'
Assign name to 'dFlatTreeFileName'
Assign name to 'dFlatTreeName'
Uncommented 'Fill_FlatTree()'

I ran it using both PROOF and single threaded.  Both gave similar errors.

The error went away when reverting to the previous version of GlueX software, namely by running:
gxclean
gxenv /group/halld/www/halldweb/html/halld_versions/version_5.18.3.xml

Here are paths to the dselector (and header file) and root tree:

/work/halld/home/dbarton/gluex/dselectors/DSelector_pi0kplamb_flat.C
/work/halld/home/dbarton/gluex/dselectors/DSelector_pi0kplamb_flat.h

/lustre19/expphy/cache/halld/RunPeriod-2018-08/analysis/ver23/tree_pi0kplamb__B4_M18/merged/tree_pi0kplamb__B4_M18_051766.root

**Comment by zihlmann** [comment]
I do not think it has anything to do with "flat trees". I get the same error after some events without even attempting to create a flat tree.

**Comment by aaust** [comment]
Is this problem still present? I just tested your DSelector both in single-threaded mode and with PROOF-Lite and the flat tree was produced correctly. I used version_5.20.0.xml. Can you confirm that? I believe the issue was fixed in PR #174 .

**Comment by dancbart** [comment]
Resolved.  I’ve tested various DSelectors as well, and flat trees are produced as expected.
